
#' Make QAQC report for a deployment
#'
#' `make_deployment_report()` Will make an html report to use while conducting
#'  quality assurance and quality control (QAQC) on a deployment.  It
#'  uses the "Auto_QC" CSV file generated by "qc_deployment()".
#'
#'  If an output ".html" file exists it will be rewritten.
#'
#' @param dir A deployment directory
#' @param quiet Set to `TRUE` for less chatter. Passed to [rmarkdown::render()].
#'
#' @return Invisibly returns the path the the QC report
#' @export
#'
#' @examples
#' \dontrun{
#'
#' example_paths <- setup_example_dir()
#' dir <- example_paths$deployment
#' qc_deployment(dir, report = FALSE)
#' report_path <-  make_deployment_report(dir)
#' }
make_deployment_report <- function(dir, quiet = FALSE) {

  #----------------------------------------------------------------------------#
  # Set paths
  #----------------------------------------------------------------------------#

  paths <- lookup_paths(deployment_dir = dir)
  site <- paths$site
  deployment_date <- paths$deployment_date

  #----------------------------------------------------------------------------#
  # Check for required input files
  #----------------------------------------------------------------------------#
  required <- c("deployment_auto_qc", "sites", "deployment_metadata")
  for (i in seq_along(required)) {
    if (!file.exists(paths[[required[i]]]))
      stop("Required ", required[i], " file is missing.  Expected at: ",
           paths[[required[i]]])
  }

  #----------------------------------------------------------------------------#
  # Knit rmarkdown into html report
  #----------------------------------------------------------------------------#

  template_rmd <- system.file("rmd/QAQC_report.rmd", package = "BuzzardsBay",
                              mustWork = TRUE)

  rmarkdown::render(input = template_rmd,
                    output_file = paths$deployment_report,
                    params = list(paths = paths),
                    quiet = quiet)


  if (FALSE) {
    # Run this manually to step through QAQC_report.Rmd
    # nolint start: object_usage_linter
    data_path <-  paths$deployment_auto_qc
    sites_path <- paths$sites
    metadata_path <- paths$deployment_metadata
    preceding_data_path <- paths$preceding_data
    # nolint end: object_usage_linter
  }

  return(invisible(paths$deployment_report))

}
