
#' Make QAQC report for a deployment
#'
#' `make_deployment_report()` Will make an html report to use while conducting
#'  quality assurance and quality control (QAQC) on a deployment.  It
#'  uses the "Auto_QC" CSV file generated by "qc_deployment()".
#'
#'  If an output ".html" file exists it will be rewritten.
#'
#' @param dir A deployment directory
#' @param quiet Set to `TRUE` for less chatter. Passed to [rmarkdown::render()].
#'
#' @return Invisibly returns the path the the QC report
#' @export
#'
#' @examples
#' \dontrun{
#'
#' example_paths <- setup_example_dir()
#' dir <- example_paths$deployment
#' qc_deployment(dir, report = FALSE)
#' report_path <-  make_deployment_report(dir)
#' }
make_deployment_report <- function(dir, quiet = FALSE) {

  #----------------------------------------------------------------------------#
  # Set paths
  #----------------------------------------------------------------------------#

  # Standardize slashes
  dir <- gsub("[/\\\\]+", .Platform$file.sep, dir)
  dir <- gsub("[/\\\\]$", "", dir) # drop trailing /

  # Directory paths
  year_dir <- cut_path_items(dir, 2)
  md_dir <- file.path(year_dir, "Metadata")

  paths <- list()

  paths <- c(paths, list(
    sites = file.path(md_dir, "sites.csv"),
    placements = file.path(md_dir, "placements.csv")
  ))

  # get deployment date date (defined as the end of deployment)
  # and site name
  # Assuming this structure
  # /<base_dir>/<year>/<site>/<year>-<month>-<day>/
  dirs <- strsplit(dir, "[/\\\\]+")[[1]]
  deployment_date <- dirs[length(dirs)]
  site <- dirs[length(dirs) - 1]
  rm(dirs)

  paths <- c(paths, list(
    auto_qc = file.path(dir, paste0("Auto_QC_", site, "_",
                                    deployment_date, ".csv")),
    prelim_qc = file.path(dir, paste0("Preliminary_QC_", site, "_",
                                      deployment_date, ".csv")),
    final_qc =  file.path(dir, paste0("QC_", site, "_",
                                      deployment_date, ".csv")),
    metadata = file.path(dir, paste0("Metadata_", site, "_",
                                     deployment_date, ".yml")),
    report = file.path(dir, paste0("QC_", site, "_", deployment_date,
                                   "_report.html"))
  ))

  required <- c("final_qc", "sites", "metadata")
  for (i in seq_along(required)) {
    if (!file.exists(paths[[i]]))
      stop("Required ", required[i], " file is missing.  Expected at: ",
           paths[[required[i]]])
  }

  template_rmd <- system.file("rmd/QAQC_report.rmd", package = "BuzzardsBay",
                              mustWork = TRUE)

  rmarkdown::render(input = template_rmd,
                    output_file = paths$report,
                    params = list(data_path = paths$auto_qc,
                                  metadata_path = paths$metadata,
                                  sites_path = paths$sites),
                    quiet = quiet)


  return(invisible(paths$repor))

}
