#' Read HOBOware details file
#'
#' Read a HOBOware details file and parse into a nested list.
#'
#' The HOBOware details file contains data on the sensor, the deployment,
#' and the calibration process.
#' Indentation level is used to indicate the hierarchy in the
#' data. `parse_hoboware_details()` parses the file into a list that
#' captures that structure.
#'
#' The approach taken is a little bit of kludge but seems to be working for
#' the files produced by the DO and Conductivity loggers.
#' `parse_hoboware_details()` first edits the details text so that it can be
#' parsed as [YAML](https://en.wikipedia.org/wiki/YAML) into an R nested list.
#' The resulting list is then cleaned by eliminating spaces and weird
#' characters from the list item names (but not values) and dropping some
#' redundant nesting.
#'
#' @note
#'
#' The sample numbers in the details files include commas (e.g 1,283 ) that
#' trip up the YAML conversion.  These are eliminated in a targeted
#' fashion - dropping commas between digits only on lines with
#' `"Max:"`, `"Min:"`, `"Avg:"`, `"Std Dev:"` or `"Samples:"`.
#' With other output files this might need to be expanded to cover more of
#' the file, but given that commas could potential delineate items in
#' a list a surgical approach was used.
#'
#' With conductivity details files some of the values are separated from the
#' field names with "=" instead of ":", used in most of the file.
#' To process these items correctly all " = "
#' are replaced with ": " before parsing as YAML.  This might create
#' unintended consequences in some fields or with other HOBOware output,
#' but it does not adversely affect any of the fields extracted by this package,
#' in [get_do_details()] or [get_cond_details()].
#'
#' `parse_hoboware_details()` is primarily intended for internal package use
#  but is exported in case it is useful.
#'
#' @param path The path to a HOBOware details file created while calibrating.
#'
#' @return A nested list with the file contents.
#' @export
#'
#' @examples
#'  file <- system.file(
#'    "extdata/2023/RB1/2023-06-09/Calibrated/DO_RB1_2023-06-09_Details.txt",
#'                      package = "BuzzardsBay")
#'  hwd <- parse_hoboware_details(file)
#'  str(hwd, max.level = 2)
#'
#'  # These are of particular interest
#'  hwd$Series_DO_Adj_Conc_mg_per_L$Dissolved_Oxygen_Assistant_Parameters |>
#'    yaml::as.yaml() |>
#'    cat()
#'
parse_hoboware_details <- function(path) {

  # Read file
  a <- readr::read_file(path)

  # Standardize on "\n" for linebreaks
  a <- gsub("[\r\n]+", "\n", a)

  # Split into a vector of lines
  a <- strsplit(a, "\n") |> dplyr::first()

  # Format as yaml
  a <- gsub("\t", " ", a)
  is_header <- !grepl("^[[:blank:]]*\u2022", a) # \u2022 is a bullet point / dot
  a <- gsub("\u2022 ", "- ", a)
  a[is_header] <- gsub(":", "", a[is_header]) # drop internal ":" in header rows
  a[is_header] <- paste0(a[is_header], ":")
  a <- a[!grepl("^Details", a)]
  # Cleanup sigma "(<sigma>)" (regardless of file encoding)
  a <- gsub("Std Dev [(].[)]", "Std Dev", a)

  # Fix = instead of : in the conductivity compensation parameters
  a <- gsub(" = ", ": ", a)


  # Remove internal commas from numbers in Series Statistics rows
  sv <- grep("(Samples:|Max:|Min:|Avg:|Std Dev:).*[[:digit:]],[[:digit:]]", a)  # nolint
  a[sv] <- gsub(",", "", a[sv])

  # Parse
  b <- yaml::read_yaml(text = a)

  # Apply recursive cleanup and simplification to standardize item names
  # and simplify the list structure.
  # Cleaning needs to happen both before and after simplification.
  c <- b |> clean_names() |> simplify_list() |> clean_names()

  return(c)
}


#' Retrieve information stored a Dissolved Oxygen calibration details file
#'
#' `get_do_details()` extracts a specific subset of the information stored in a
#' details file generated by HOBOware during DO calibration.
#'
#' @param path The path to a details file created by HOBOware during
#' calibration.
#' @return A nested list containing of a small subset of the information in
#' `file`.
#' @seealso
#' * [get_cond_details()] for a similar function to process
#' a HOBOware details file generated while calibrating conductance/salinity.
#' * [parse_hoboware_details()] for a function to read and format all
#' of the information in a HOBOware details file.
#' @export
#'
#' @examples
#'  file <- system.file(
#'    "extdata/2023/RB1/2023-06-09/Calibrated/DO_RB1_2023-06-09_Details.txt",
#'                      package = "BuzzardsBay")
#'  do_cal  <- get_do_details(file)
#'  cat(yaml::as.yaml(do_cal))
#'
get_do_details <- function(path) {

  # Parse file into list
  d <- parse_hoboware_details(path)

  # initialize result list
  result <- list()


  #----------------------------------------------------------------------------#
  # Dissolved Oxygen Assistant Parameters
  #----------------------------------------------------------------------------#

  # Now allowing the first level in the list to include _Conc_ or not.
  do_series_name <- grep(pattern = "Series_DO_Adj_[Conc_]*mg_per_L",
                         x = names(d), value = TRUE)
  if (is.null(do_series_name)) {
    stop("Couldn't find a \"Series_Do_Adj_mg_per_L\" item in DO_details file.")
  }

  doap_name <- "Dissolved_Oxygen_Assistant_Parameters"
  if (!doap_name %in% names(d[[do_series_name]])) {
    stop("Couldn't find \"", doap_name, "\" in the \"",
         do_series_name, "\" section of the DO details file.")
  }

  doap <- d[[do_series_name]][[doap_name]]

  if (is.null(doap)) {
    stop("HOBOware Dissolved oxygen details file (", path, ")",
         " was not parsed properly or doesn't have the expected contents.
         Could not find the dissolved oxygen assistant parameters.")
  }

  # Dissolved Oxygen Assistant Parameters to keep:
  doap_targets <-
    c("Start_time",
      "Start_DO_conc",
      "Start_temperature_C",
      "Start_salinity_ppt",
      "Start_meter_per_titration_value_mg_per_L",
      "Start_salinity_correction",
      "End_time",
      "End_DO_conc",
      "End_temperature_C",
      "End_meter_per_titration_value_mg_per_L")

  if (!all(doap_targets %in% names(doap)))
    stop("The DO details file from HOBOware was parsed wrong or is missing ",
         "expected calibration information.")
  doap <- doap[doap_targets]
  names(doap) <- tolower(names(doap))
  names(doap) <-  gsub("_per_", "_", names(doap))

  result$do_calibration <- doap

  #----------------------------------------------------------------------------#
  # Deployment info
  #----------------------------------------------------------------------------#
  dep_info_name <- "Deployment_Info"

  if (! dep_info_name %in% names(d[[do_series_name]])) {
    stop("Could not find \"", dep_info_name, "\" in the \"", do_series_name,
         "\" section of the DO details file.")
  }

  dep <- d[[do_series_name]][[dep_info_name]]

  dep_targets <- c("Full_Series_Name",
                   "Launch_Name",
                   "Launch_Time",
                   "Logging_Interval",
                   "Calibration_Date",
                   "Calibration_Gain",
                   "Calibration_Offset")

  if (!all(dep_targets %in% names(dep)))
    stop("The DO details file from HOBOware was parsed wrong or is missing ",
         "expected deployment information.")
  dep <- dep[dep_targets]
  names(dep) <- tolower(names(dep))

  # Create numeric logging interval
  a <- dep$logging_interval
  a <- gsub("[^[:digit:]]+", ":", a)
  a <- gsub("^:|:$", "", a)   # trim leading and trainling
  hms <- strsplit(a, ":") |> unlist() |> as.numeric()
  min <- (hms * c(1 / 60, 1, 60)) |> sum()
  dep$logging_interval_min <- min


  result$do_deployment <- dep

  #----------------------------------------------------------------------------#
  # Device info
  #----------------------------------------------------------------------------#


  dev <- d[[do_series_name]]$Devices$Device_Info
  if (is.null(dev))
    stop("Expected to find \"", do_series_name, " - Devices - Device_Info\" ",
         "section in DO Details file.")
  dev_targets <- c("Product",
                   "Serial_Number",
                   "Version_Number",
                   # "Manufacturer",
                   # "Device_Memory",
                   "Header_Created")
  if (!all(dev_targets %in% names(dev)))
    stop("The DO details file from HOBOware was parsed wrong or is missing ",
         "expected device information.")
  dev <- dev[dev_targets]
  names(dev) <- tolower(names(dev))

  result$do_device <- dev

  #----------------------------------------------------------------------------#

  return(result)
}


#' Retrieve information from a conductivity calibration details file
#'
#' `get_cond_details()` extracts a specific subset of the information stored
#' in a details file generated by HOBOware during conductivity/salinity
#' calibration.
#'
#' @param path The path to a details file created by HOBOware during
#' conductivity calibration.
#' @return A nested list containing of a small subset of the information in
#' `file`.
#' @seealso
#' * [get_do_details()] for a similar function to process
#' a HOBOware details file generated while calibrating dissolved oxygen.
#' * [parse_hoboware_details()] for a function to read and format all
#' of the information in a HOBOware details file.
#' @export
#'
#' @examples
#'  file <- system.file(
#'    "extdata/2023/RB1/2023-06-09/Calibrated/Cond_RB1_2023-06-09_Details.txt",
#'                      package = "BuzzardsBay")
#'  do_cal  <- get_cond_details(file)
#'  cat(yaml::as.yaml(do_cal))
#'
get_cond_details <- function(path) {

  # Parse file into list
  d <- parse_hoboware_details(path)

  # initialize result list
  result <- list()

  #----------------------------------------------------------------------------#
  #  Conductivity Compensation Parameters
  #----------------------------------------------------------------------------#

  # Extract
  salinity_series_name <- grep("Series_Salinity.*_ppt", names(d), value = TRUE)

  if (length(salinity_series_name) != 1)
    stop("Couldn't identify a Salinity Series in Conductivity/Salinity ",
         "details file")

  ccp  <- d[[salinity_series_name]]$Conductivity_Compensation_Parameters
  if (is.null(ccp)) {
    stop("HOBOware conductivity details file (", path, ")",
         " was not parsed properly or does not have the expected contents.",
         "Could not find \"Conductivity_Compenstation_Parameters\" section",
         "within \"", salinity_series_name, "\"")
  }

  # Conductivity Compensation Parameters to keep:
  ccp_targets <-
    c("Calibration_points",
      "Start_cal_cond",
      "Start_cal_temp",
      "Start_cal_time",
      "End_cal_cond",
      "End_cal_temp",
      "End_cal_time")

  miss <- ccp_targets[!ccp_targets %in% names(ccp)]

  if (!length(miss) %in% c(0, 3))  # allowed to be missing one of start or end
    stop("The Conductivity details file from HOBOware was parsed wrong ",
         "or is missing expected calibration information.",
         "Could not find \"",
         paste(miss, collapse = "\", \""),
         " in the conductivity compensation parameters.")


  # Replace missing elements with NA's
  if (length(miss) > 0) {
    l <- vector(mode = "list", length = length(miss))
    names(l) <- miss
    for (i in seq_along(l)) {
      l[[i]] <- NA
    }
    ccp <- c(ccp, l)
  }


  ccp <- ccp[ccp_targets]

  # Separate units from numbers in value fields
  # e.g `Start_cal_cond = "41877.00 μS/cm"`  to `Start_cal_cond = 41877.00`

  # Leave time and calibration points out
  problem_fields <- ccp_targets[!grepl("time|points", ccp_targets)]
  for (field in problem_fields) {
    a <- ccp[[field]]
    a <- gsub("[^-.[:digit:]]", "", a) # drop non-number characters
    a <- as.numeric(a)
    ccp[[field]] <- a
  }
  names(ccp) <- tolower(names(ccp))

  result$cond_calibration <- ccp


  #----------------------------------------------------------------------------#
  # Deployment info
  #----------------------------------------------------------------------------#

  dep <- d[[salinity_series_name]]$Deployment_Info

  if (is.null(dep))
    stop("HOBOware conductivity details file (", path, ")",
         " was not parsed properly or does not have the expected contents. ",
         "Could not find \"Deployment_Info\" section",
         "within \"", salinity_series_name, "\"")



  dep_targets <- c("Full_Series_Name",
                   "Launch_Name",
                   "Launch_Time",
                   "Logging_Interval")

  miss <- setdiff(dep_targets, names(dep))

  if (!length(miss) == 0)
    stop("The Conductivity details file from HOBOware was parsed wrong ",
         "or is missing expected calibration information.",
         "Could not find \"",
         paste(miss, collapse = "\", \""),
         " in the Salinity series deployment infomation.")

  dep <- dep[dep_targets]
  names(dep) <- tolower(names(dep))

  # Create numeric logging interval
  a <- dep$logging_interval
  a <- gsub("[^[:digit:]]+", ":", a)
  a <- gsub("^:|:$", "", a)   # trim leading and trainling
  hms <- strsplit(a, ":") |> unlist() |> as.numeric()
  min <- (hms * c(1 / 60, 1, 60)) |> sum()
  dep$logging_interval_min <- min


  result$cond_deployment <- dep


  #----------------------------------------------------------------------------#
  # Device info
  #----------------------------------------------------------------------------#

  dev <- d[[salinity_series_name]]$Devices$Device_Info

  if (is.null(dev))
    stop("HOBOware conductivity details file (", path, ")",
         " was not parsed properly or does not have the expected contents. ",
         "Could not find \"Devices\" - \"Device_Info\" section",
         "within \"", salinity_series_name, "\"")

  dev_targets <- c("Product",
                   "Serial_Number",
                   "Version_Number",
                   # "Manufacturer",
                   # "Device_Memory",
                   "Header_Created")

  miss <- setdiff(dev_targets, names(dev))

  if (!length(miss) == 0)
    stop("The Conductivity details file from HOBOware was parsed wrong ",
         "or is missing expected calibration information.",
         "Could not find \"",
         paste(miss, collapse = "\", \""),
         " in the Salinity series device infomation.")

  dev <- dev[dev_targets]
  names(dev) <- tolower(names(dev))

  result$cond_device <- dev


  return(result)
}



# Private helper function to recursively cleanup list item names
# Used by parse_hoboware_details()
clean_names <- function(x, spaces = 0) {
  if (!inherits(x, "list"))
    return(x)
  n <- names(x)
  n <- gsub(" ", "_", n) # replace spaces with _
  n <- gsub("/", "_per_", n) # replace "/" with "_per_"
  n <- gsub("%", "pct", n)  # replace "%" with "_pct"
  n <- gsub("[()\u00B0,]", "", n) # drop these symbols \u00B0 is the deg symbol
  n <- gsub("_+", "_", n) # drop repeated _
  names(x) <- n

  for (i in seq_along(x)) {
    x[[i]] <- clean_names(x[[i]], spaces = spaces + 1)
  }
  return(x)
}


# Private Helper function to eliminates intermediate single item lists
# that lack names.
# I couldn't figure out how to edit the yaml to get rid of these so am
# cleaning them up after converting to a list
# Used by parse_hoboware_details()
# nolint start:cyclocomp_linter
simplify_list <- function(x) {
  if (!is.list(x))
    return(x)

  for (i in seq_along(x)) {
    y <- x[[i]]

    # Eliminate single element unamed lists that contain a single element
    # list, replace with the lower level list item
    if (is.list(y) && length(y) == 1 && is.na(names(x[i]))) {
      x[i] <- y
      names(x)[i] <- names(y)
    }

    # Eliminate single element unamed lists that contain a character,
    #  replace with an empty, named list item)
    if (is.character(y) && length(y) == 1 && is.na(names(x[i]))) {
      names(x)[i] <- y
      x[[i]] <- NA
    }
  }

  for (i in seq_along(x)) {
    x[[i]] <- simplify_list(x[[i]])
  }
  return(x)
}
# nolint end
